#!/usr/bin/env python
import serial                     # we need to import the pySerial stuff to use
import sys
from time import sleep, time
import random
import numpy
import dxl2

servo_id = [0,1,2]
SPEED_LIMIT = 0.5

dynamixel = dxl2.Dynamixel('/dev/ttyUSB0', 1000000)
speed = 0

print dynamixel.get_position(servo_id)
dynamixel.set_speed(servo_id,[speed, speed, speed])
goal = [int(arg) for arg in sys.argv[1:4]]
dynamixel.set_goal(servo_id,goal)

